name: CI/CD Pipeline for Gaza Uni Portal

on:
  push:
    branches: [ "main" ] # سيعمل النظام تلقائياً عند الرفع على فرع main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          # نستخدم الأسرار التي قمت بإنشائها في إعدادات المستودع
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Backend
        uses: docker/build-push-action@v5
        with:
          context: .
          target: backend-production # المرحلة النهائية للباك-إند
          push: true
          # استخدام اسم المستخدم mohdlehya23 الظاهر في حسابك
          tags: mohdlehya23/uni-backend:latest

      - name: Build & Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: .
          target: frontend-production # المرحلة النهائية للفرونت-إند
          push: true
          build-args: |
            VITE_API_URL=http://localhost:5000/api
          tags: mohdlehya23/uni-frontend:latest
